### ISSUE TITLE
Deploying libmxnet package fails

### ISSUE THREAD

**Issue by joseph-wakeling-sociomantic** [sociomantic-tsunami/mxnet#3]
The build log reports a "conflict creating version" (from https://travis-ci.org/sociomantic-tsunami/mxnet/jobs/255618351):

```
[33mDeploying application[0m
+docker run -ti --rm -v /home/travis:/home/travis -v /home/travis/build/sociomantic-tsunami/mxnet:/home/travis/build/sociomantic-tsunami/mxnet -w /home/travis/build/sociomantic-tsunami/mxnet -u 2000 -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8 -e USER -e HOME -e DEBIAN_FRONTEND -e RAILS_ENV -e RACK_ENV -e MERB_ENV -e JRUBY_OPTS -e JAVA_HOME -e CI -e CONTINUOUS_INTEGRATION -e TRAVIS_OS_NAME -e TRAVIS_STACK_LANGUAGES -e TRAVIS_BRANCH -e TRAVIS_SUDO -e TRAVIS_GHC_DEFAULT -e TRAVIS_GHC_ROOT -e TRAVIS_PRE_CHEF_BOOTSTRAP_TIME -e TRAVIS_FILTERED -e TRAVIS_PULL_REQUEST_BRANCH -e TRAVIS_PULL_REQUEST_SLUG -e TRAVIS_CABAL_DEFAULT -e TRAVIS_COMMIT_MESSAGE -e TRAVIS_CABAL_ROOT -e TRAVIS_STACK_NAME -e TRAVIS_STACK_JOB_BOARD_REGISTER -e TRAVIS_REPO_SLUG -e TRAVIS_BUILD_ID -e TRAVIS_COMMIT_RANGE -e TRAVIS -e TRAVIS_ALLOW_FAILURE -e TRAVIS_EVENT_TYPE -e TRAVIS_STACK_FEATURES -e TRAVIS_BUILD_NUMBER -e TRAVIS_BUILD_DIR -e TRAVIS_SECURE_ENV_VARS -e TRAVIS_TAG -e TRAVIS_JOB_ID -e TRAVIS_COMMIT -e TRAVIS_PULL_REQUEST -e TRAVIS_STACK_TIMESTAMP -e TRAVIS_JOB_NUMBER -e TRAVIS_UID -e TRAVIS_PULL_REQUEST_SHA -e TRAVIS_LANGUAGE -e TRAVIS_STACK_NODE_ATTRIBUTES -e TRAVIS_TEST_RESULT -e DIST -e BINTRAY_USER -e BINTRAY_KEY beaver beaver/bin/bintray/upload -N -d sociomantic-tsunami/mxnet/libmxnet *.deb
jfrog bt version-create --desc=libmxnet v0.10.0.s1-rc1 --vcs-tag=v0.10.0.s1-rc1 --released=2017-07-20T13:02:36.000Z sociomantic-tsunami/mxnet/libmxnet/v0.10.0.s1-rc1
[Info] Creating version...
[Error] Bintray response: 409 Conflict
{
  "message": "Conflict Creating Version"
}
jfrog bt upload --publish=true --override=false --deb=trusty/prerelease/*.deb *.deb sociomantic-tsunami/mxnet/libmxnet/v0.10.0.s1-rc1
[Info] Verifying repository mxnet exists...
[Info] Verifying package libmxnet exists...
[Info] Verifying version v0.10.0.s1-rc1 exists...
[Info] Collecting files for upload:. Done.
[Info] [Thread 0] Uploading artifact: build/devel/pkg/libmxnet_0.10.0.s1-rc1-trusty_amd64.deb
[Error] [Thread 0] Bintray response: 400 Bad Request
{
  "message": "Unable to upload files: '*.deb' is not a valid value for deb_architecture"
}
[Info] Uploaded 0 artifacts.
[Error] Failed uploading 1 artifacts.
Error: Could not upload file *.deb to sociomantic-tsunami/mxnet/libmxnet/v0.10.0.s1-rc1!
Script failed with status 1

travis_fold:end:dpl.3
failed to deploy
```

**Comment by leandro-lucarella-sociomantic** [comment]
Ah, this is because the version was created but the package failed to upload because of the problem uploading the package (I can't find the issue now). That should be resolved before we retry anyway.

**Comment by joseph-wakeling-sociomantic** [comment]
@leandro-lucarella-sociomantic TBH I think I didn't ever appreciate the distinction between those concerns: we had a failure, you asked me to file an issue, this is that issue.  Sorry if it's confusing multiple things together.

Do you need me to file a separate issue for the package upload failure?  Or can we take this issue as covering everything together?

**Comment by leandro-lucarella-sociomantic** [comment]
I'm still uncertain, to be honest at a first glance it looks like a travis issue, that for some reason it's not passing arguments for the deploy script via shell (so there is no expansion on wildcards). I'm almost certain I mentioned this, this is why I thought there was another issue, but maybe I did via PM.

**Comment by leandro-lucarella-sociomantic** [comment]
This also seems to have worked fine in the past with other projects, for example:

* https://github.com/sociomantic-tsunami/tangort/blob/v1.8.0-alpha1/.travis.yml#L31-L32
* https://travis-ci.org/sociomantic-tsunami/tangort/jobs/244582427#L187

**Comment by leandro-lucarella-sociomantic** [comment]
Oh! Your travis file is incorrect, you have to provide the path to the .deb file!
```yml
script: beaver bintray upload -d sociomantic-tsunami/mxnet/libmxnet build/last/pkg/*.deb
```

Not just `*.deb`.

**Comment by leandro-lucarella-sociomantic** [comment]
We could improve the error detection in beaver, can you create an issue for that? So at least you get some sort of early "file not found '*.deb'" error.

Is all more confusing since the bintray tool will do a recursive search for `*.deb`, so it doesn't fail when the tool tries to find the file itself.

**Comment by joseph-wakeling-sociomantic** [comment]
OK, I'll fix things up and redo.

Mind if I kill the tag, BTW, in the circumstances? :-P

**Comment by leandro-lucarella-sociomantic** [comment]
Unrelated but related. I recomend creating a special branch for the version we are packaging. In other repos we just have a `sociomantic` branch. So it's easier to find in which branch the packaging scripts are. You could have some sort of `v0.10.x-socio` if you think you'll add the packaging scripts to several branches.

**Comment by joseph-wakeling-sociomantic** [comment]
@leandro-lucarella-sociomantic I already created a `v0.10.x` branch to package from ;-)

**Comment by leandro-lucarella-sociomantic** [comment]
> @leandro-lucarella-sociomantic I already created a v0.10.x branch to package from ;-)

I would find a way to indicate is a sociomantic branch somehow, because for people not familiar with the repo is impossible to tell otherwise. You could also change the default branch.

**Comment by leandro-lucarella-sociomantic** [comment]
> OK, I'll fix things up and redo.
> 
> Mind if I kill the tag, BTW, in the circumstances? :-P

I would create a `-rc2`, I don't think one should kill `rc`s that were faulty, they are expected to have problems, that's why they are not final.

**Comment by joseph-wakeling-sociomantic** [comment]
I'd just forgotten it was an `-rc`.  Too many things on the old neural network ;-)
